# Generated by Django 4.1.7 on 2023-03-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.IntegerField()),
                ('data2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCORE_TYPE_CHOICES', models.CharField(choices=[('fact', 'Fact'), ('forecast', 'Forecast')], max_length=10)),
                ('qliq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qliq_scores', to='sheet.quantity')),
                ('qoil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qoil_scores', to='sheet.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qoil_total', models.IntegerField(blank=True, null=True)),
                ('qliq_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.company')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_sheet', to='sheet.scores')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_sheet', to='sheet.scores')),
            ],
        ),
    ]
